---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.13.7
  values:
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      ingress:
        enabled: true
        hosts: ['grafana.mc.playhrzn.com']
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/appName: Grafana
          forecastle.stakater.com/icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/grafana.png
          kubernetes.io/ingress.class: "nginx"
          external-dns.alpha.kubernetes.io/hostname: grafana.mc.playhrzn.com
    nodeExporter:
      serviceMonitor:
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: instance
