---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux-helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux-helm-operator
      annotations:
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: flux-helm-operator
      volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
            defaultMode: 0400
      containers:
        - name: flux-helm-operator
          # There are no ":latest" images for helm-operator. Find the most recent
          # release or image version at https://hub.docker.com/r/fluxcd/helm-operator/tags
          # and replace the tag here.
          image: docker.io/fluxcd/helm-operator:1.2.0@sha256:91dc5e42f9aed503e4eae8663b43ecbc1bab9164dd8a5ad3e1421db4656e1c62
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3030
          livenessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
          args:
            - --tiller-namespace=kube-system
            - --enabled-helm-versions=v3
            - --charts-sync-interval=30s
